name: form-example

on:
 workflow_dispatch:
  inputs:
   input_node:
    description: 'Input Node Name.'
    required: true
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Read options from JSON file
        uses: actions/checkout@v3
      - name: Read options from JSON file
        id: read_options
        run: |
          options=$(jq -r '.options' choices.json)
          echo "::set-output name=options::$options"
