name: form-example

on:
 schedule:
    - cron: '10 * * * *'
 workflow_dispatch:
  inputs:
   input_node:
    description: 'Input Node Name.'
    required: true
    
jobs:
  excel-graph:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python environment
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install xlrd xlwt openpyxl
    - name: Generate Excel file and graph
      run: |
        echo "schedule"
        cd ./src
        python generate_excel.py
     - name: Upload Excel file
      uses: actions/upload-artifact@v3
      with:
        name: excel-graph
        path: example.xls
