name: form-example

on:
 workflow_dispatch:
  inputs:
   input_node:
    description: 'Input Node Name.'
    required: true
 
    
jobs:
  excel-graph:
    env:
      #input_compo: "Tlmf"
      input_compo: '["Tlmf","Lcd","Bsm","DestJdg","OmiArb"]'
    runs-on: windows-latest
    outputs:
      list:  ${{ steps.create_unittest_brach.outputs.list }}
      compo_testtype:  ${{ steps.create_unittest_brach.outputs.compo_testtype }}
      targetcompolist:  ${{ steps.create_unittest_brach.outputs.targetcompolist }}
    steps:
    - uses: actions/checkout@v3
    - name: Create UnitTest Branch
      id: create_unittest_brach
      run: |
       #サンプル１
       #echo '["Tlmf","Lcd","Bsm","DestJdg","OmiArb"]' | jq -c
       #list=$(echo '["Tlmf","Lcd","Bsm","DestJdg","OmiArb"]' | jq -c)
       #echo "targetcompo=${list}" >> $GITHUB_OUTPUT
       #サンプル２(単体コンポ)
       #targetcompo=$(echo '["${{env.input_compo}}"]' | jq -c)
       #echo "${targetcompo}"
       #echo "targetcompo=${targetcompo}" >> $GITHUB_OUTPUT
       #サンプル３(全コンポ)
       $list='["Tlmf","Lcd","Bsm","DestJdg","OmiArb"]'
       echo "list=${list}" >> $GITHUB_OUTPUT
       $targetcompo='["Tlmf","Lcd","Bsm","DestJdg","OmiArb"]'
       echo "${targetcompo}"
       echo "0"
       $compo_testtype = @()
       echo "1"
       foreach ($compo in ($targetcompo | ConvertFrom-Json)) {
         echo "compo=$compo"
         if ($compo -ne "Bsm"){
           $test_type = "csv"
         }else{
           $test_type = "mix"
         }
         $compo_testtype += @( @{Name = $compo; Type = $test_type})
       }
       foreach ($item in $compo_testtype) {
         echo("Name: " + $item.Name + ", Type: " + $item.Type)
       }
       echo compo_testtype=${compo_testtype}| Out-File -Append -FilePath $env:GITHUB_OUTPUT

       #testtype='["csv","mix","csv","gtest","csv"]'
       #echo "testtype=${testtype}" >> $GITHUB_OUTPUT

       #echo "input_compo=${env.input_compo}"
       #echo "input_compo=${{fromJson( env.input_compo )}}"
       $targetcompo = $compo_testtype | ForEach-Object { echo $_.Name }
       echo "$targetcompo"
       echo "targetcompolist=${targetcompo}" >> $GITHUB_OUTPUT
   
  Exec_GTestConvTool:
    runs-on: ubuntu-latest
    needs: excel-graph
    strategy:
      max-parallel: 2
      matrix:
        compolist: ${{needs.excel-graph.outputs.targetcompolist}}${{fromJson( needs.excel-graph.outputs.list )}}
    steps:
      - name: Clean self-hosted runner
        run: |
          echo "Exec_GTestConvTool"
          echo ${ matrix.compolist }
          

  Exec_ECU-Build:
    runs-on: ubuntu-latest
    needs: excel-graph
    strategy:
      max-parallel: 2
      matrix:
        compolist: ${{needs.excel-graph.outputs.targetcompolist}}
    steps:
      - name: Clean self-hosted runner
        run: |
          echo "Exec_ECU-Build"
          echo ${{ matrix.compolist }}
