name: C Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - name: Create new Branch
      env: 
        BRANCH_NAME: "test"
      run: | 
        git branch $BRANCH_NAME 
        git checkout $BRANCH_NAME 
        git push --set-upstream origin $BRANCH_NAME
    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y build-essential
    - name: Build C code
      run: sh build.sh
      working-directory: ./src
    - name: Execute binary
      run: ./hello_world
      working-directory: ./src
