name: form-example

on:
 workflow_dispatch:
  inputs:
   input_node:
    description: 'Input Node Name.'
    required: true
    
jobs:
  excel-graph:
    runs-on: ubuntu-latest
    outputs:
      targetcompo:  ${{ steps.create_unittest_brach.outputs.targetcompo }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python environment
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install xlrd xlwt openpyxl
        echo "schedule"
    - name: Generate Excel file and graph
      run: |
        #cd ./src
        #python generate_excel.py
     #- name: Upload Excel file
     # uses: actions/upload-artifact@v3
     # with:
     #   name: excel-graph
     #   path: example.xls
    - name: Create UnitTest Branch
      id: create_unittest_brach
      run: |
       echo '["Tlmf","Lcd","Bsm","DestJdg","OmiArb"]' | jq -c
       list=$(echo ["Tlmf","Lcd","Bsm","DestJdg","OmiArb"]' | jq -c)
       echo "targetcompo=${list}" >> $GITHUB_OUTPUT
       
       #targetcompo[0]=Tlmf
       #targetcompo[1]=Lcd
       #targetcompo[2]=Bsm
       #targetcompo[3]=DestJdg
       #targetcompo[4]=OmiArb
       #echo ${targetcompo[0]}
       #echo ${targetcompo[1]}
       #echo ${targetcompo[2]}
       #echo ${targetcompo[3]}
       #echo ${targetcompo[4]}
   
  Exec_GTestConvTool:
    runs-on: ubuntu-latest
    needs: excel-graph
    strategy:
      max-parallel: 2
      matrix:
        #compolist: ${{ needs.excel-graph.outputs.targetcompo }}
        compolist: ${{fromJson( needs.excel-graph.outputs.targetcompo )}}
    steps:
      - name: Clean self-hosted runner
        run: |
          echo "Exec_GTestConvTool"
          echo ${{ matrix.compolist }}
    #      echo ${{ excel-graph.outputs.targetcompo }}


  Exec_ECU-Build:
    runs-on: ubuntu-latest
    needs: excel-graph
    #strategy:
    #  max-parallel: 2
    #  matrix:
    #    compolist: ${{ needs.excel-graph.outputs.targetcompo }}
    steps:
      - name: Clean self-hosted runner
        run: |
          echo "Exec_ECU-Build"
    #      echo ${{ matrix.compolist }}
        
