name: form-example

on:
 workflow_dispatch:
  inputs:
   input_node:
    description: 'Input Node Name.'
    required: true
    options: ${ fromJson((steps.read_options.outputs.options) }
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Read options from JSON file
        id: read_options
        run: |
          options=$(jq -r '.options' options.json)
          echo "::set-output name=options::$options"
